services:
  user_service:
    build: ./user-service
    container_name: user_service
    ports:
      - "5001:5001"

  order_service:
    build: ./order-service
    container_name: order_service
    ports:
      - "5002:5002"
    depends_on:
      - user_service

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - user_service
      - order_service
